// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj-7QEKr55ZWh6mxMsuzOavgQSdxRBfA4',
    appId: '1:382623732391:web:0776e3c2d983fc212a8182',
    messagingSenderId: '382623732391',
    projectId: 'hr-attendee',
    authDomain: 'hr-attendee.firebaseapp.com',
    storageBucket: 'hr-attendee.appspot.com',
    measurementId: 'G-FKM5YG1N04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzrBbjlAF6XyRcRPv8XQ1YfRn2-GCNpwg',
    appId: '1:382623732391:android:c02dc4fffa732e702a8182',
    messagingSenderId: '382623732391',
    projectId: 'hr-attendee',
    storageBucket: 'hr-attendee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDppvWTj5DbZ90liZp1fHBMaJHcHD0UO2g',
    appId: '1:382623732391:ios:591ca52e221cac7a2a8182',
    messagingSenderId: '382623732391',
    projectId: 'hr-attendee',
    storageBucket: 'hr-attendee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDppvWTj5DbZ90liZp1fHBMaJHcHD0UO2g',
    appId: '1:382623732391:ios:591ca52e221cac7a2a8182',
    messagingSenderId: '382623732391',
    projectId: 'hr-attendee',
    storageBucket: 'hr-attendee.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj-7QEKr55ZWh6mxMsuzOavgQSdxRBfA4',
    appId: '1:382623732391:web:bece7a76e95182612a8182',
    messagingSenderId: '382623732391',
    projectId: 'hr-attendee',
    authDomain: 'hr-attendee.firebaseapp.com',
    storageBucket: 'hr-attendee.appspot.com',
    measurementId: 'G-N098TP4PY1',
  );
}
